### ISSUE TITLE
`SVG is not defined` when combined with `vue3-apexcharts`

### ISSUE THREAD

**Issue by adamndev** [e-chan1007/nuxt-monaco-editor#21]
Hey, thanks for the Nuxt plugin 👌🏻

Any ideas why installing this alongside `vue3-apexcharts` gives this error?

[Reproduction link](https://stackblitz.com/edit/nuxt-monaco-apex-svg-issue?file=package.json)

![Screenshot 2023-01-27 at 18 48 36](https://user-images.githubusercontent.com/13210094/215169883-95e69de1-2278-4791-9ddc-efff5a5c8cc4.png)

**Comment by e-chan1007** [comment]
The loader of `SVG.js` (which `apexcharts` depends on) seems to conflict with the one of `monaco-editor`.
This error should be fixed in [`v1.1.3`](https://github.com/e-chan1007/nuxt-monaco-editor/releases/tag/v1.1.3) by delaying the loading timings of `monaco-editor`.

**Comment by adamndev** [comment]
Thank you for looking at this, but still seeing this same error and the one below when I add the `nuxt-monaco-editor` in the same app and navigate to a page. I've updated the reproduction link above.

The chart is a `.client` component, and I've also tried like this to see if I can delay the loading of SVG library but no luck there.

```
components: {
  ApexChart: defineAsyncComponent(() => import('vue3-apexcharts')),
},
```

I really appreciate the help @e-chan1007 👍🏻

**Comment by e-chan1007** [comment]
You should also add a plugin like this:

```ts
// ~/plugins/apexcharts.client.ts

import VueApexCharts from 'vue3-apexcharts';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueApexCharts);
});

/*
  (The same code without nuxt)
  https://github.com/apexcharts/vue3-apexcharts#usage

  import VueApexCharts from "vue3-apexcharts";

  const app = createApp(App);
  app.use(VueApexCharts);
*/
```

This will load the SVG library correctly and `<apexchart>` will also be added automatically.

**Comment by adamndev** [comment]
Works perfectly, thanks!

Seems the issue was with trying to import ApexCharts on demand instead of just importing it globally as per the docs.
